# Site settings
title: Yet another dev blog # site title
description: >- # site description
  A collection of articles related to my development.. To be precised later.
lang: en-US # default lang
timezone: Europe/Paris # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Cyril Six # author name
  bio: >- # tell to the world
    PhD student at Kalray company (embedded processor designer), working on
    scheduling optimizations in the CompCert compiler for interlocked
    VLIW architectures.
  username: potterman28wxcv # author username
  github: sixcy
  twitter: 
  facebook: 
  email: CS4566@gmail.com # your contact adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# Url settings
url: 
baseurl:
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
